language: perl
matrix:
    fast_finish: true
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -n Test::Simple"
    - "cpanm -n Test::More"
    - "cpanm -n File::Spec::Functions"
    - "cpanm -n File::Basename"
    - "cpanm -n Locale::Maketext::Lexicon"
    - "cpanm -n Locale::Maketext"
    - "cpanm -n --installdeps ."
    - "cpanm -qn Test::Requires::Git"
    - "cpanm -qn Devel::Cover::Report::Codecov"
script:
    perl Makefile.PL && make test
after_success:
    cover -test -report codecov
