language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -n Mojolicious"
    - "cpanm -n MojoX::JSON::RPC"
    - "cpanm -n Guard"
    - "cpanm -n JSON"
    - "cpanm -n Data::UUID"
    - "cpanm -n Test::More"
    - "cpanm -n Test::Mojo"
    - "cpanm -n Test::MockModule"
    - "cpanm -n Test::MockObject"
    - "cpanm -n Time::Out"
    - "cpanm -n Class::Method::Modifiers"
    - "cpanm -n --installdeps ."
script:
    perl Makefile.PL && make test
